[package]
name = "markov"
version = "0.1.0"
authors = ["Envis10n <envis10n@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
markov_core = {path = "../markov_core"}